version: 2
updates:
  - package-ecosystem: npm
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: uv
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
    directory: "/fine-arts-jr-review"
    schedule:
      interval: weekly
